import type { StructureTabContent } from '~/utils/structureContent'

/**
 * Prose pages migrated from the old site that are not part of a structure unit.
 *
 * Same file shape as a structure tab (`sections[]` of sanitised HTML plus provenance), so both
 * render through `SharedStructureUnitTabBody`. Generated by
 * `knpu-university-be/migration/pages/migrate_page.py` — edit the JSON or re-run the script,
 * never this file.
 *
 * These stay static rather than becoming Directus items because the client does not ask to edit
 * them; the pages that *are* editable use the `documents` collection instead.
 */
export type StaticPageContent = StructureTabContent & { title?: string }

const pageModules = import.meta.glob<{ default: StaticPageContent }>('../content/pages/*.json')

/**
 * Body for one static page. Falls back to Ukrainian when there is no translation — as with the
 * structure pages, the old site was Ukrainian-only.
 */
export async function loadStaticPage(
  slug: string,
  locale: string,
): Promise<{ content: StaticPageContent; locale: string } | null> {
  for (const candidate of locale === 'uk' ? ['uk'] : [locale, 'uk']) {
    const loader = pageModules[`../content/pages/${slug}.${candidate}.json`]
    if (!loader) continue
    const module = await loader()
    return { content: module.default, locale: candidate }
  }
  return null
}
