import manifest from '~/content/structure/manifest.json'
import { findStructureUnit } from '~/utils/structure'

/**
 * Static content for the institute / faculty pages, migrated from the old Drupal site.
 *
 * Two kinds of file live under `app/content/structure/`:
 *
 * - `manifest.json` — small, imported eagerly. Says which tabs a unit has and carries its
 *   contact block, so the tab bar and the route guard can both be synchronous.
 * - `<unit>/<tab>.<locale>.json` — the bodies. Loaded lazily, one chunk each, because a single
 *   tab can be a few hundred kilobytes of migrated HTML and no other page should pay for it.
 *
 * Everything here is generated by `knpu-university-be/migration/structure-pages/` — edit the
 * pipeline (or the JSON), not this file, to change content.
 */

/** Tab order is fixed and shared by every unit; the ids double as URL segments. */
export const STRUCTURE_TAB_IDS = [
  'home',
  'admission',
  'structure',
  'history',
  'education',
  'science',
  'students',
  'news',
  'cooperation',
] as const

export type StructureTabId = (typeof STRUCTURE_TAB_IDS)[number]

export interface StructureUnitContacts {
  dean?: string
  deanEn?: string
  /** Personal page of the dean, usually a Google Site. */
  deanUrl?: string
  position?: string
  positionEn?: string
  address?: string
  addressEn?: string
  phone?: string
  email?: string
  facebook?: string
  instagram?: string
}

export interface StructureUnitManifestEntry {
  /** Page on the old site this content came from, kept for provenance. */
  legacyUrl?: string
  capturedAt?: string
  /** Tabs that have a body file. `home` is listed here too; `structure`/`news` are derived. */
  tabs?: StructureTabId[]
  contacts?: StructureUnitContacts
}

export interface StructureTabSection {
  heading?: string
  html: string
}

export interface StructureTabLink {
  label: string
  url: string
}

export interface StructureTabContent {
  sections: StructureTabSection[]
  links?: StructureTabLink[]
  sourceUrls?: string[]
  capturedAt?: string
}

const unitManifest = manifest as Record<string, StructureUnitManifestEntry>

export function structureUnitManifest(slug: string): StructureUnitManifestEntry | undefined {
  return unitManifest[slug]
}

/**
 * Lazy loaders, one per content file. Without `eager` each file becomes its own async chunk,
 * so nothing here reaches the entry bundle.
 */
const tabModules = import.meta.glob<{ default: StructureTabContent }>('../content/structure/*/*.json')

function tabModuleKey(unit: string, tab: StructureTabId, locale: string): string {
  return `../content/structure/${unit}/${tab}.${locale}.json`
}

function isTabId(value: string): value is StructureTabId {
  return (STRUCTURE_TAB_IDS as readonly string[]).includes(value)
}

/**
 * Tabs to show for a unit, in canonical order.
 *
 * A tab appears only when it has something to show: a migrated body, subdivisions (Структура),
 * or a news category (Новини). An empty tab reads as a broken page, so it is hidden and its URL
 * 404s rather than rendering nothing.
 */
export function structureUnitTabs(slug: string): StructureTabId[] {
  const unit = findStructureUnit(slug)
  if (!unit) return []

  const withBody = new Set(structureUnitManifest(slug)?.tabs ?? [])
  const available = new Set<StructureTabId>(['home'])

  for (const tab of withBody) available.add(tab)
  if (unit.items.length > 0 || unit.associations?.length) available.add('structure')
  if (unit.newsCategorySlug ?? unit.slug) available.add('news')

  return STRUCTURE_TAB_IDS.filter(tab => available.has(tab))
}

/** Route guard for `/university/structure/<unit>/<tab>`. Synchronous by design. */
export function isStructureTabRoute(unit: string, tab: string): boolean {
  if (!isTabId(tab) || tab === 'home') return false
  return structureUnitTabs(unit).includes(tab)
}

/**
 * Body for one tab in one locale. Falls back to Ukrainian when the English file is missing —
 * the old site only ever translated the faculty landing pages.
 */
export async function loadStructureTabContent(
  unit: string,
  tab: StructureTabId,
  locale: string,
): Promise<{ content: StructureTabContent; locale: string } | null> {
  for (const candidate of locale === 'uk' ? ['uk'] : [locale, 'uk']) {
    const loader = tabModules[tabModuleKey(unit, tab, candidate)]
    if (!loader) continue
    const module = await loader()
    return { content: module.default, locale: candidate }
  }
  return null
}
