import manifest from '~/content/structure/manifest.json'
import { findStructureUnit } from '~/utils/structure'

/**
 * Static content for the institute / faculty pages, migrated from the old Drupal site.
 *
 * Two kinds of file live under `app/content/structure/`:
 *
 * - `manifest.json` — small, imported eagerly. Says which tabs a unit has and carries its
 *   contact block, so the tab bar and the route guard can both be synchronous.
 * - `<unit>/<tab>.<locale>.json` — the bodies. Loaded lazily, one chunk each, because a single
 *   tab can be a few hundred kilobytes of migrated HTML and no other page should pay for it.
 *
 * Everything here is generated by `knpu-university-be/migration/structure-pages/` — edit the
 * pipeline (or the JSON), not this file, to change content.
 */

/** Tab order is fixed and shared by every unit; the ids double as URL segments. */
export const STRUCTURE_TAB_IDS = [
  'home',
  'admission',
  'structure',
  'history',
  'education',
  'science',
  'students',
  'doctoral',
  'regulations',
  'news',
  'announcements',
  'cooperation',
] as const

export type StructureTabId = (typeof STRUCTURE_TAB_IDS)[number]

/**
 * Tabs whose body is a list of documents rather than migrated prose.
 *
 * The unit page renders `SharedDocumentList` for these, reading the section named here out of
 * the shared `documents` collection, so editors maintain them the same way as every other
 * document page on the site.
 */
export const STRUCTURE_DOCUMENT_TABS: Partial<Record<StructureTabId, string>> = {
  regulations: 'postgraduate-regulations',
}

export interface StructureUnitContacts {
  dean?: string
  deanEn?: string
  /** Personal page of the dean, usually a Google Site. */
  deanUrl?: string
  position?: string
  positionEn?: string
  address?: string
  addressEn?: string
  phone?: string
  email?: string
  facebook?: string
  instagram?: string
}

export interface StructureUnitManifestEntry {
  /** Page on the old site this content came from, kept for provenance. */
  legacyUrl?: string
  capturedAt?: string
  /** Tabs that have a body file. `home` is listed here too; `structure`/`news` are derived. */
  tabs?: StructureTabId[]
  /** Tabs backed by the `documents` collection — see `STRUCTURE_DOCUMENT_TABS`. */
  documentTabs?: StructureTabId[]
  /** Tabs that are a news feed for one category, keyed by tab id. */
  categoryTabs?: StructureTabId[]
  /** Category slug per `categoryTabs` entry; defaults to the unit's own news category. */
  categorySlugs?: Partial<Record<string, string>>
  /**
   * Tab captions that differ for this unit. The shared captions are written for faculties
   * («Вступнику», «Студентство»), which reads wrong for a department whose audience is
   * postgraduates, so a unit may name its own tabs.
   */
  tabLabels?: Partial<Record<StructureTabId, { uk: string; en?: string }>>
  contacts?: StructureUnitContacts
}

/**
 * One member of a unit's leadership, lifted out of the migrated «Деканат» table by
 * `migration/structure-pages/6_extract_people.py` so it can render as a card row.
 */
export interface StructureUnitPerson {
  /** `/assets/<uuid>`; null where the old site had no portrait for that person. */
  photo: string | null
  position: string | null
  name: string
  degree: string | null
  profileUrl: string | null
}

export interface StructureTabSection {
  heading?: string
  html: string
  people?: StructureUnitPerson[]
  /** Caption that stood above the extracted block, e.g. «Деканат». */
  peopleHeading?: string | null
  /**
   * Render the section as a drop-down instead of a plain block — the old site wrapped long
   * topics in `[collapse]` shortcodes and the client asked to keep that reading experience.
   * Only `SharedStaticPageBody` honours it so far.
   */
  collapsible?: boolean
  /** Drop-downs nested inside this one; the legacy editor allowed one level. */
  children?: StructureTabSection[]
}

export interface StructureTabLink {
  label: string
  /** Address on another site. */
  url?: string
  /** Route on this site — used where the legacy link pointed at a page we now host ourselves. */
  path?: string
}

export interface StructureTabContent {
  sections: StructureTabSection[]
  links?: StructureTabLink[]
  sourceUrls?: string[]
  capturedAt?: string
}

const unitManifest = manifest as Record<string, StructureUnitManifestEntry>

export function structureUnitManifest(slug: string): StructureUnitManifestEntry | undefined {
  return unitManifest[slug]
}

/**
 * Lazy loaders, one per content file. Without `eager` each file becomes its own async chunk,
 * so nothing here reaches the entry bundle.
 */
const tabModules = import.meta.glob<{ default: StructureTabContent }>('../content/structure/*/*.json')

function tabModuleKey(unit: string, tab: StructureTabId, locale: string): string {
  return `../content/structure/${unit}/${tab}.${locale}.json`
}

function isTabId(value: string): value is StructureTabId {
  return (STRUCTURE_TAB_IDS as readonly string[]).includes(value)
}

/**
 * Tabs to show for a unit, in canonical order.
 *
 * A tab appears only when it has something to show: a migrated body, subdivisions (Структура),
 * or a news category (Новини). An empty tab reads as a broken page, so it is hidden and its URL
 * 404s rather than rendering nothing.
 */
export function structureUnitTabs(slug: string): StructureTabId[] {
  const unit = findStructureUnit(slug)
  if (!unit) return []

  const manifestEntry = structureUnitManifest(slug)
  const withBody = new Set(manifestEntry?.tabs ?? [])
  const available = new Set<StructureTabId>(['home'])

  for (const tab of withBody) available.add(tab)
  for (const tab of manifestEntry?.documentTabs ?? []) available.add(tab)
  for (const tab of manifestEntry?.categoryTabs ?? []) available.add(tab)
  if (unit.items.length > 0 || unit.associations?.length) available.add('structure')
  if (unit.newsCategorySlug ?? unit.slug) available.add('news')

  return STRUCTURE_TAB_IDS.filter(tab => available.has(tab))
}

/** Route guard for `/university/structure/<unit>/<tab>`. Synchronous by design. */
export function isStructureTabRoute(unit: string, tab: string): boolean {
  if (!isTabId(tab) || tab === 'home') return false
  return structureUnitTabs(unit).includes(tab)
}

/**
 * Body for one tab in one locale. Falls back to Ukrainian when the English file is missing —
 * the old site only ever translated the faculty landing pages.
 */
export async function loadStructureTabContent(
  unit: string,
  tab: StructureTabId,
  locale: string,
): Promise<{ content: StructureTabContent; locale: string } | null> {
  for (const candidate of locale === 'uk' ? ['uk'] : [locale, 'uk']) {
    const loader = tabModules[tabModuleKey(unit, tab, candidate)]
    if (!loader) continue
    const module = await loader()
    return { content: module.default, locale: candidate }
  }
  return null
}

/**
 * Caption for one tab of one unit — the unit's own wording where it has one, otherwise the
 * shared translation. English falls back to Ukrainian, as elsewhere in the migrated content.
 */
export function structureTabLabelOverride(
  slug: string,
  tab: StructureTabId,
  locale: string,
): string | undefined {
  const label = structureUnitManifest(slug)?.tabLabels?.[tab]
  if (!label) return undefined
  return (locale === 'en' ? label.en : label.uk) ?? label.uk
}
